# -*- coding: utf-8 -*-
"""Utilities.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bPwlVq7fR68b7sr_7PcrIzg5Q7xc39ZR
"""

from keras.preprocessing.image import ImageDataGenerator

def cifar10_augment(trinData):
  dataAugment = ImageDataGenerator(
    featurewise_center=False, samplewise_center=False, samplewise_std_normalization=False, featurewise_std_normalization=False, zca_whitening=False,  
    rotation_range=45, width_shift_range=0.2, height_shift_range=0.2, horizontal_flip=True, vertical_flip=False) 
  dataAugment.fit(trinData)
  return dataAugment

def cifar100_augment(trainData):
  dataAugment = ImageDataGenerator( featurewise_center=False, samplewise_center=False, featurewise_std_normalization=False, samplewise_std_normalization=False,  
            zca_whitening=False, rotation_range=15, width_shift_range=0.1, height_shift_range=0.1, horizontal_flip=True, vertical_flip=False) 
  dataAugment.fit(trainData)
  return dataAugment